language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit
  - vendor/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
