language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

script:
  - pwd
  - composer install
  - echo $TRAVIS_PHP_VERSION
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then vendor/bin/phpunit; else composer test; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then vendor/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN; fi
