language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

jobs:
  include:
  - php: 7.4
    env: RUN_SONAR=true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit
  - $RUN_SONAR && vendor/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
