language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

# before_script:
#   - curl https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=1.10.10
#   - composer install --dev

script:
  - pwd
  - composer test
  - vendor/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
